Repository dantebben/nox-uv, pull requests merged in 2025-06, with the labels that each got.

#37 validate that venv backend is set to uv if user requests uv parameters
  noxfile.py
  pyproject.toml
  src/nox_uv/__init__.py
  tests/subproject/noxfile.py
  tests/subproject/uv.lock
  tests/test_lib.py
  uv.lock
Labels: bug, enhancement

#38 Add `uv_only_groups` example to README
  README.md
Labels: documentation

#41 Update README description
  README.md
Labels: documentation

#50 Fix test suite execution on Windows
  tests/subproject/noxfile.py
Labels: bug

#48 Set `UV_PYTHON` to session's interpreter path
  src/nox_uv/__init__.py
Labels: enhancement

#46 Update dependencies
  .github/workflows/ci.yml
  pyproject.toml
  tests/subproject/uv.lock
  uv.lock
Labels: dependencies

#45 Log uv environment changes
  src/nox_uv/__init__.py
Labels: enhancement

#54 Fix example session name
  README.md
Labels: documentation

#59 Document that `uv.lock` is validated by default
  README.md
Labels: documentation
